// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UI_Core from "./core/UI_Core.bs.js";

var valueOfDevice = UI_Core.valueOfDevice;

var greaterThan = UI_Core.greaterThan;

var lessThan = UI_Core.lessThan;

var all = UI_Core.all;

var xxs = UI_Core.xxs;

var xs = UI_Core.xs;

var sm = UI_Core.sm;

var md = UI_Core.md;

var lg = UI_Core.lg;

var xl = UI_Core.xl;

var valueByDevice = UI_Core.valueByDevice;

var createStyles = UI_Core.createStyles;

var createResponsiveStyles = UI_Core.createResponsiveStyles;

var Base;

var Box;

var Flex;

export {
  valueOfDevice ,
  greaterThan ,
  lessThan ,
  all ,
  xxs ,
  xs ,
  sm ,
  md ,
  lg ,
  xl ,
  valueByDevice ,
  createStyles ,
  createResponsiveStyles ,
  Base ,
  Box ,
  Flex ,
  
}
/* No side effect */
