// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Ancestor from "@rescriptbr/ancestor/src/Ancestor.bs.js";
import * as Ancestor_Base from "@rescriptbr/ancestor/src/components/Ancestor_Base.bs.js";

function App(Props) {
  return React.createElement(Ancestor_Base.make, {
              display: [Ancestor.xxs("flex")],
              p: [Ancestor.xxs(2)],
              children: React.createElement("img", undefined)
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
