name: Create version and update main branch

on:
  workflow_dispatch:
    inputs:
        versionType:
          description: Version type
          required: true
          default: 'patch'
          type: choice
          options:
            - patch
            - minor
            - major

jobs:
  create-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Merge main and dev
      - run: |
          git checkout main
          git rebase dev
      
      - name: Generate new version ${{ github.event.inputs.versionType }}
        run: npm version ${{ github.event.inputs.versionType }}

      - name: Push the tags
        run: git push origin main --tags

      - name: Sync main and dev
        run: |
         git checkout dev
         git rebase main
         git push origin dev 
