name: Publish package on NPM

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: Package name
        required: true
        default: "core"
        type: choice
        options:
          - core
          - ui
          - bindings

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: cd packages/${{ github.event.inputs.packageName }} && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
